import express from "express";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import User from "../models/User.js";
import { authenticateToken } from "../middleware/auth.js";
const router=express.Router();
function createToken(user){return jwt.sign({userId:user._id.toString(),role:user.role},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||"1d"});}
router.post("/register",async(req,res)=>{try{const{name,email,password,role="student"}=req.body;if(!name||!email||!password)return res.status(400).json({success:false,message:"Name, email and password are required"});if(!["student","driver","admin"].includes(role))return res.status(400).json({success:false,message:"Invalid role"});const existingUser=await User.findOne({email:email.toLowerCase()});if(existingUser)return res.status(409).json({success:false,message:"User with this email already exists"});const hashedPassword=await bcrypt.hash(password,10);const user=await User.create({name,email,password:hashedPassword,role});return res.status(201).json({success:true,message:"User registered successfully",user:{id:user._id,name:user.name,email:user.email,role:user.role}});}catch(error){return res.status(500).json({success:false,message:"Registration failed",error:error.message});}});
router.post("/login",async(req,res)=>{try{const{email,password}=req.body;if(!email||!password)return res.status(400).json({success:false,message:"Email and password are required"});const user=await User.findOne({email:email.toLowerCase()}).select("+password");if(!user)return res.status(401).json({success:false,message:"Invalid email or password"});const passwordMatches=await bcrypt.compare(password,user.password);if(!passwordMatches)return res.status(401).json({success:false,message:"Invalid email or password"});return res.status(200).json({success:true,message:"Login successful",token:createToken(user),user:{id:user._id,name:user.name,email:user.email,role:user.role}});}catch(error){return res.status(500).json({success:false,message:"Login failed",error:error.message});}});
router.get("/me",authenticateToken,async(req,res)=>{try{const user=await User.findById(req.user.userId).select("-password");if(!user)return res.status(404).json({success:false,message:"User not found"});return res.status(200).json({success:true,user});}catch(error){return res.status(500).json({success:false,message:"Failed to fetch user",error:error.message});}});
export default router;
